#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Class-Unload
Version  : 0.11
Release  : 30
URL      : https://cpan.metacpan.org/authors/id/I/IL/ILMARI/Class-Unload-0.11.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IL/ILMARI/Class-Unload-0.11.tar.gz
Summary  : 'Unload a class'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Class-Unload-license = %{version}-%{release}
Requires: perl-Class-Unload-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Class::Inspector)
BuildRequires : perl(Test::Requires)

%description
This archive contains the distribution Class-Unload,
version 0.11:
Unload a class

%package dev
Summary: dev components for the perl-Class-Unload package.
Group: Development
Provides: perl-Class-Unload-devel = %{version}-%{release}
Requires: perl-Class-Unload = %{version}-%{release}

%description dev
dev components for the perl-Class-Unload package.


%package license
Summary: license components for the perl-Class-Unload package.
Group: Default

%description license
license components for the perl-Class-Unload package.


%package perl
Summary: perl components for the perl-Class-Unload package.
Group: Default
Requires: perl-Class-Unload = %{version}-%{release}

%description perl
perl components for the perl-Class-Unload package.


%prep
%setup -q -n Class-Unload-0.11
cd %{_builddir}/Class-Unload-0.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Class-Unload
cp %{_builddir}/Class-Unload-0.11/LICENSE %{buildroot}/usr/share/package-licenses/perl-Class-Unload/952325f8249de5f60bef0cd2ca6a97cdf82cf5c0
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::Unload.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Class-Unload/952325f8249de5f60bef0cd2ca6a97cdf82cf5c0

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
